SeikoStudentCouncil/SlackArchiveBot

ArchiveMessage.js
とりあえずメソッドあるから書いたけど、format が... そもそも後々の処理的にメッセージ欄にファイルリンクを直接書かない方がいいかな
あとちょっと頑張れるなら Google Drive に保存してそのリンクを貼りたい
@miko-misa comment か Code Review お願い
=> [update] archive URLs of files

ArchiveMessage.js
Change the column numbers
close #8
=> [fix] Change the column numbers

ArchiveMessage.js
=> [fix] Get tokens and define variables by them

ArchiveMessage.js
=> [fix] Set the getMax{Rows/Columns}()

ArchiveMessage.js
=> [fix] Fix variable name `botToken`

ArchiveMessage.js
=> Fix mention format

ArchiveMessage.js
=> [fix] Fix tokens definition

ArchiveMessage.js
File.alternateLink is not a func but a method.
close #30
=> [fix] change file.alternateLink into a method

ArchiveMessage.js
=> [hotfix] Continue `if (url == '')`

ArchiveMessage.js
=> [clean] Delete ` != ''`

ArchiveMessage.js
=> [fix] fix getAllMessageInChannel()

ArchiveMessage.js
=> [fix] change file type from `file` to `driveFile`

.github/workflows/cd.yml
=> [hotfix] Add `--force` option to `clasp push`

ArchiveMessage.js
=> [hotfix] Use `headers; Authorization`

ArchiveMessage.js
=> [update] Sort channels by their name

ArchiveMessage.js
=> [update] Update `backUpContinue`

ArchiveMessage.js
=> [hotfix] try-catch pass

ArchiveMessage.js
=> [fix] Fix `null` problem on #49 comment

ArchiveMessage.js
=> [hotfix] Fix undefined variable name `threadTs`

ArchiveMessage.js
=> [hotfix] Introduce channelIndex

ArchiveMessage.js
=> [hotfix] Undefined `index`

ArchiveMessage.js
=> Delete useless codes and improve great performance!

ArchiveMessage.js
As a concrete process in `doPost(e)`, I'll implement `updateArchives()` later.
=> [update] Get sheet ID from command arguments, check token

.github/workflows/create_branch.yml
=> [dev/add] Add `CreateBranch`

ArchiveMessage.ts
=> [#59] [fix] Fix channels limit in `getAllChannels()`

ArchiveMessage.ts
=> [hotfix] change `ss` to `ss_main`

ArchiveMessage.ts
=> [improve] implement insert sort using binary search

ArchiveMessage.ts
=> [hotfix] fix `updateArchives2` (maybe)

ArchiveMessage.ts
=> [hotfix] fix UpdateMessageInChannel
